language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ivalexig/docker-react-pipeline -f Dockerfile.dev .

script:
  - docker run -e CI=true ivalexig/docker-react-pipeline npm run test
